; [pytest]
; pythonpath = .
; asyncio_mode = strict

[pytest]
asyncio_mode = auto

addopts = -m "not integration"

markers =
    integration: tests that communicate with external services such as Gemini